version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-dev
        container_name: avrae_io
        ports:
            - "8000:8080"
        environment:
            - NODE_ENV=development